# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: launchpad

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/launchpad
    binary: launchpad
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ecoker/launchpad/internal/cli.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - repository:
      owner: ecoker
      name: homebrew-tap
    name: launchpad
    homepage: "https://github.com/ecoker/launchpad"
    description: "AI-powered coding instruction scaffolder"
    license: "MIT"
    binaries: ["launchpad"]

release:
  github:
    owner: ecoker
    name: launchpad
  draft: false
  prerelease: auto
